### PR TITLE
Export nfo file functionality

### PR DESCRIPTION
**Pull request by xybydy**

### CODE REVIEW

**Comment by xybydy** [comment]
Playback quality prompt were constantly pops up even the movies was on. So I based the version on Kodi source not the one on Github since it was functionally better than the one on Github.

**Comment by cguZZman** [comment]
Can you leave that part out of your PR? I will fix it before I publish it. I see where the issue is.

**Comment by xybydy** [comment]
Done that. But I will keep my fork as before until I see your fix works well.

**Comment by cguZZman** [comment]
Please update your PR to be on top of the latest changes.
Also, don't change the versions or any info in the addon.xml. I will assign the version number as needed.
Same for the change in the common drive module.

**Comment by xybydy** [comment]
Closing this request. Made a new branch and request.

**Pull request closed without merging**
